language: ruby
rvm:
 - 3.2
script: ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
deploy:
  provider: pages:git # this differs from schibsted
  token:
    secure: "mUKZyJCCOPhZM0Bl9ItOzRkNp35kgOzKtKMKi0qdIOKfwSicdUcBZeU4w9/6rtOYP8oUm00fZsjy+OTZvmypjaSr5dHARL85NtVUH4obdBQJXPGP0jgUT9kLMSYMBoHJC6MlghRrlhxeSmNVpIHZk2tSOJ9AfSsoqKAonSo+dPbks3khlpSfXxJ5IGWJNmws6SSbTnHVTJMEN7NVqGNcvngXAaKy6eMA9GMfXpVeqLzD9Hsd+Yfw90RXTQuNtpUxzGDE+01pyQYR70BvPhOAP4Vxvgt18UKXt/9S+4pl60vumXxc5rRIgT82ogGK4zT+uaNScMjAC3zGOUCft6vPLHE75LhACpwC5CBebTALOIc1LG4laHiWcEx330KbYuHeAkhrKQHgAH+nDJmIVCuRqlFUTa0FbU3A+fQZkFhzdV0Ypz3TWO4OvSmjBsflmjOd0fnrp2L/g6wFQeXIx9PNZY20sygsQdNMkEsQUY1fnWf+P1L8BpWZY8bW6hpmaMtKfrNkkjKviUPlBdf0r5blIXcdKjawIFGWFmgTlU5MhOpSXtI9s1DAL91q0Wftap1CLa+HsrCf2gy1udh1/U1KyEtnRjNWu2AkNA7ELkvNIEpgltNa2inagpa3pfSh/lZjhubxzoKhYU2CTkPsGhBnw4VWDsbBwlbXhLos8hS4yhI="
    # secure: "GcGCgo3WXZTaqt5dFUDeofXsO8snUx3Bs6bH8ePZ3U69gxGVHibL0Fou5xnMFR2CF05EnDf8vbfNEQbXBuc4W27GThbtNIrVRqGVFmpggIH27bFbBEj33gAStY3thWyw9G945v3UhaPZAiXjvkKMFkvL1oOQJ2rXVapn5p9N7p6j+xU+R8hvouFl5WwWtxBJCitYeoHo65nKGameH66iPC1f2yPhPwOGoJ66L9IJzJu+PxygCdAY/5aDgMrUxxpqlz2bknFHdB1OG5C5g5d18wdLIhJX1cUOF+3hz5BcE/S/+8OczPnOsYfP15LFqFwThg+jFJHVu0z2paC3qcDfyMoICifOvtyEnzZh42QCeC0tlWzsKJ5lcoIYXX3tldI4E9r5WWL7HxVsjl9Ba5I5zl0nO0cAifns6O5m8iLZqy5wtjbbBj3LRoc7/OOBOT5AyCxSz7n6BgAsv7Qtsh7ZprfDlUCwSnhK9RvDokB2x5Ys3dx350/D4xtTd8dZSUwU6Bc1GRZuBlBO/IILN5yAcMs/0lCjcDH9I3zK80JEp4lvFTxbvw3Ow41XPZ0wswn/80o6IuvT9u0Syhru5jqmURoJ+XPkK50qC/i8JckhzvtvRakLDbp7wTbClWGeuq8SirJBiOzpcbTl1OT4IMwB4fUTxX5xDC4TwCG9ETFl1eI="
  verbose: true
  cleanup: false
  keep_history: true
  url: github.com
  local_dir: pages/
  on:
    branch:
    - main
    - deploy
